# [git aliases]
alias ga='git add'
alias gac='git a . ;and git commit -am'
alias gb='git branch'
alias gbD='git branch -D'
alias gbl='git branch -a --color=always | less -R'
alias gbU='git branch -u'
alias gc='git commit'
alias gclean='git clean'
alias gcm='git commit -m'
alias gcam='git commit -am'
alias gchp='git cherry-pick'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcoo='git checkout --ours'
alias gd='git diff'
alias gdn='git diff --name-only'
alias gdsf='g dsf'
alias gdsfc='gdsf --cached'
alias gdt='git difftool --tool='
alias gdT='git diff-tree --no-commit-id --name-only -r'
alias gfp='git fetch -p && git pull'
alias gk='gitk --all --first-parent --remotes --reflog --author-date-order'
alias gl='git log --graph --abbrev-commit --decorate --date=local'
alias glf='git log --graph --abbrev-commit --decorate --date=local --first-parent'
alias gm='git merge --no-commit --no-ff'
alias gma='git merge --abort'
alias gms='git merge --no-commit --squash'
alias gmt='git mergetool --tool='
alias gp='git push'
alias gpl='git pull'
alias gpo='git push origin'
alias gpu='git push upstream'
alias grh='git reset HEAD'
alias grhh='git reset --hard'
alias grhhh='git reset --hard HEAD'
alias gs='git status'
alias gsa='g sa'
alias gsho='git show'
alias gsl='git stash list'
alias gss="git stash save $(date '+%b %d, %Y at %I:%M %p')"
alias gtrack='git update-index --no-assume-unchanged'
alias guntrack='git update-index --assume-unchanged'
alias findExec='find $1 -type $2 -name $3 -exec grep -HniF --color=always $4 "{}" \;' 

function gpnb () {
    git push --set-upstream git@gitlab.com:cmcfarlane/$(git rev-parse --show-toplevel | xargs basename).git $(git rev-parse --abbrev-ref HEAD)
}
